### ISSUE TITLE
Elementor nulled issue

### ISSUE THREAD

**Issue by hassaanmehar** [sharafdin/nulled-elementor-pro#4]
I added the nulled, but when I did, it broke my whole site. I removed the nulled, but the issue remains; it only shows the header and footer on all pages.

**Comment by sharafdin** [comment]
> I added the nulled, but when I did, it broke my whole site. I removed the nulled, but the issue remains; it only shows the header and footer on all pages.

it works well for me. can you please check your wordpress site if the issue is something else.

**Comment by moonshin3sa** [comment]
I also encountered this issue. You can reproduce the issue by create page with new tools such as flex gridbox of a new elementor version. After install this elementor pro all of new tools was removed. 
If a whole page is created by new elementor tools, only header and footer remains like this issue. I guess it was confict in versioning

**Comment by sharafdin** [comment]
> I also encountered this issue. You can reproduce the issue by create page with new tools such as flex gridbox of a new elementor version. After install this elementor pro all of new tools was removed. If a whole page is created by new elementor tools, only header and footer remains like this issue. I guess it was confict in versioning

maybe. i will try to update asap.

**Comment by sharafdin** [comment]
> I also encountered this issue. You can reproduce the issue by create page with new tools such as flex gridbox of a new elementor version. After install this elementor pro all of new tools was removed. If a whole page is created by new elementor tools, only header and footer remains like this issue. I guess it was confict in versioning

updated thanks
