### ISSUE TITLE
nulled elementor pro

### ISSUE THREAD

**Issue by usmanakramsaab** [sharafdin/nulled-elementor-pro#5]
i installed the plugin elementor pro but this plugin not up to date my website facing critial error

**Comment by sharafdin** [comment]
> i installed the plugin elementor pro but this plugin not up to date my website facing critial error

i will update and i hope it will work for you Insha'Allah!

**Comment by ktbrasil** [comment]
i installed too and was outdated and then failed to update saying download unauthorised

**Comment by sharafdin** [comment]
> i installed too and was outdated and then failed to update saying download unauthorised

yup. you can;t update automatically, i will try to release new version asap.
