### ISSUE TITLE
Post Carousel Widget not working

### ISSUE THREAD

**Issue by arifislam-26** [sharafdin/nulled-elementor-pro#7]
![Screenshot 2024-10-28 203500](https://github.com/user-attachments/assets/34a3220d-f5ea-4cdc-ae12-443ab8cf2712)

**Comment by arifislam-26** [comment]
@sharafdin

**Comment by arifislam-26** [comment]
Ok thank you, sir 
I am Waiting for the upload

**Comment by sharafdin** [comment]
> Ok thank you, @sharafdin sir I am Waiting for the upload, sorry how can I get it?

I will upload for free Insha'Allah!

**Comment by sharafdin** [comment]
uploaded thanks
